# Generated by Django 4.0.4 on 2022-08-08 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_category_location_purpose_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='category',
            new_name='cat',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='location',
            new_name='loc',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='purpose',
            new_name='pur',
        ),
    ]
