# Generated by Django 4.0.4 on 2022-08-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_rename_category_place_cat_rename_location_place_loc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purpose2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pur_tag', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='place',
            name='pur',
        ),
        migrations.DeleteModel(
            name='Purpose',
        ),
    ]
