# Generated by Django 4.0.4 on 2022-08-08 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_purpose2_remove_place_pur_delete_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purpose1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pur_tag', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='place',
            old_name='p_image',
            new_name='image',
        ),
        migrations.AddField(
            model_name='place',
            name='pur2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.purpose2'),
        ),
        migrations.AddField(
            model_name='place',
            name='pur1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.purpose1'),
        ),
    ]
