# Generated by Django 4.0.4 on 2022-08-10 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_place_latitude_place_longitude_alter_place_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='longitude',
            new_name='lng',
        ),
    ]
