# Generated by Django 4.0.4 on 2022-08-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_rename_latitude_place_lat_rename_longitude_place_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='lng',
            field=models.TextField(blank=True, null=True),
        ),
    ]
