# Generated by Django 4.0.4 on 2022-08-12 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_place_image'),
        ('backend', '0009_alter_place_lat_alter_place_lng'),
    ]

    operations = [
    ]
