# Generated by Django 4.0.4 on 2022-08-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_place_lat_alter_place_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
