# Generated by Django 4.0.4 on 2022-08-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_merge_20220812_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
