# Generated by Django 4.0.4 on 2022-08-12 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_place_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='lat',
            new_name='latlng',
        ),
        migrations.RemoveField(
            model_name='place',
            name='lng',
        ),
    ]
