# Generated by Django 4.0.4 on 2022-08-12 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_rename_lat_place_latlng_remove_place_lng'),
        ('backend', '0013_category_location_purpose1_purpose2_place'),
    ]

    operations = [
    ]
