# Generated by Django 4.0.4 on 2022-08-17 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_place_address_alter_place_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='info',
        ),
    ]
