# Generated by Django 4.0.4 on 2022-08-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_remove_place_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
