# Generated by Django 4.0.4 on 2022-08-17 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_merge_20220817_1515'),
        ('backend', '0014_merge_20220817_2005'),
        ('backend', '0017_place_info'),
    ]

    operations = [
    ]
