# Generated by Django 4.0.4 on 2022-08-17 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_merge_0014_merge_20220817_2005_0017_place_info'),
        ('backend', '0018_merge_20220817_2029'),
    ]

    operations = [
    ]
