# Generated by Django 4.0.4 on 2022-08-24 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_merge_20220817_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='latlng',
            new_name='menu',
        ),
        migrations.AddField(
            model_name='place',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='curation',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CurationList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp1', models.TextField(blank=True, null=True)),
                ('exp2', models.TextField(blank=True, null=True)),
                ('exp3', models.TextField(blank=True, null=True)),
                ('exp4', models.TextField(blank=True, null=True)),
                ('exp5', models.TextField(blank=True, null=True)),
                ('place1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_1', to='backend.place')),
                ('place2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_2', to='backend.place')),
                ('place3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_3', to='backend.place')),
                ('place4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_4', to='backend.place')),
                ('place5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_5', to='backend.place')),
            ],
        ),
        migrations.AddField(
            model_name='curation',
            name='curation_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.curationlist'),
        ),
    ]
